<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IUS.ExamSystem.Domain\IUS.ExamSystem.Domain.csproj" />
    <ProjectReference Include="..\IUS.ExamSystem.Infrastructure\IUS.ExamSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
